---
abstract: 'Compare numerical values by limiting number of decimal places'
author:
  - 'moznion <moznion@gmail.com>'
build_requires:
  Test::Builder::Tester: 1.22
  Test::Exception: 0.31
  Test::More: 0.98
configure_requires:
  Module::Build: 0.40
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-LimitDecimalPlaces
no_index:
  directory:
    - inc
provides:
  Test::LimitDecimalPlaces:
    file: lib/Test/LimitDecimalPlaces.pm
    version: 0.01
requires:
  Carp: 0
  Exporter: 0
  Test::Builder: 0.98
  parent: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/moznion/Test--LimitDecimalPlaces.git
version: 0.01
